# Generated by Django 3.0.6 on 2020-05-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('more', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='more',
            name='image',
            field=models.CharField(default='image', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='more',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
