# Generated by Django 3.0.6 on 2020-05-30 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('more', '0002_auto_20200522_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='more',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
