# Generated by Django 3.0.6 on 2020-06-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('more', '0003_auto_20200530_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='more',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
