# Generated by Django 3.0.6 on 2020-06-02 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('more', '0004_auto_20200602_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='more',
            name='published_date',
        ),
    ]
