# Generated by Django 4.1.7 on 2023-03-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoons',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
