# Generated by Django 4.1.7 on 2023-03-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0003_alter_cartoons_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoons',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
