# Generated by Django 4.1.7 on 2023-03-11 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=40)),
                ('image', models.FileField(blank=True, null=True, upload_to='collection/')),
            ],
            options={
                'db_table': 'stories',
            },
        ),
    ]
