# Generated by Django 4.1.7 on 2023-03-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_stories_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='description',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
