# Generated by Django 4.1.7 on 2023-03-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_alter_stories_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='featured',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
