# Generated by Django 4.1.7 on 2023-03-28 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_alter_stories_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stories',
            name='featured',
        ),
    ]
