# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-20 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bandsongs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
                ('group', models.CharField(choices=[('Pentagons', 'Pentagons'), ('Kordz', 'Kordz'), ('Cykics', 'Cykics')], default='Pentagons', max_length=15)),
            ],
            options={
                'ordering': ['-artist'],
                'db_table': 'bandsongs',
            },
        ),
    ]
