# Generated by Django 4.1.7 on 2023-04-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displays',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
