# Generated by Django 4.1.7 on 2023-05-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=40, null=True)),
                ('image', models.ImageField(null=True, upload_to='media/photos')),
            ],
            options={
                'db_table': 'photos',
            },
        ),
    ]
