# Generated by Django 4.1.7 on 2023-05-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
            ],
            options={
                'db_table': 'quotes',
            },
        ),
        migrations.RenameModel(
            old_name='Home',
            new_name='HomeImages',
        ),
        migrations.AlterModelTable(
            name='homeimages',
            table='homeimages',
        ),
    ]
