# Generated by Django 4.1.7 on 2023-05-03 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_quotes_rename_home_homeimages_alter_homeimages_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeImages',
        ),
    ]
