# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-20 03:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsStories',
            new_name='News',
        ),
        migrations.AlterModelTable(
            name='news',
            table='news',
        ),
    ]
