# Generated by Django 3.0.6 on 2020-06-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200618_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='story',
            field=models.FileField(upload_to='collection/'),
        ),
    ]
