# Generated by Django 3.0.6 on 2020-06-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='')),
                ('published_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'photos',
            },
        ),
    ]
