# Generated by Django 3.0.6 on 2020-06-02 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='published_date',
        ),
    ]
